spring:
  mail:
    host: 'smtp.gmail.com'
    username: 'corder.carl@gmail.com'
    password: 'yreqeflmfpblxpcz'
    properties:
      mail:
        smtp:
          auth: 'true'
          socketFactory:
            port: '465'
            class: 'javax.net.ssl.SSLSocketFactory'
            fallback: 'false'
          ssl:
            enable: 'true'
mail:
  test:
    username:
      to: 'carlcorder@hotmail.com'